# Labeler configuration for automatic PR labeling

# Component labels
"component: ui":
  - changed-files:
    - any-glob-to-any-file: 
      - 'components/**/*'
      - 'app/**/*.tsx'
      - 'app/**/*.css'

"component: data":
  - changed-files:
    - any-glob-to-any-file: 'data/**/*'

"component: hooks":
  - changed-files:
    - any-glob-to-any-file: 'hooks/**/*'

"component: lib":
  - changed-files:
    - any-glob-to-any-file: 'lib/**/*'

# Type labels
"type: documentation":
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'public/**/*.txt'

"type: configuration":
  - changed-files:
    - any-glob-to-any-file:
      - '*.config.*'
      - '*.json'
      - '.github/**/*'
      - 'tsconfig.json'

"type: assets":
  - changed-files:
    - any-glob-to-any-file:
      - 'public/**/*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
      - '**/*.ico'

"type: styling":
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - 'tailwind.config.*'
      - 'postcss.config.*'

# Dependency labels
"dependencies":
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'

# CI/CD labels
"ci/cd":
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'

# Size labels (automatically added by size)
"size: small":
  - changed-files:
    - count-comparison: '<' 10

"size: medium":
  - changed-files:
    - count-comparison: '>=' 10
    - count-comparison: '<' 30

"size: large":
  - changed-files:
    - count-comparison: '>=' 30
